COLUMNS:
  model: object
  year: int64
  price: int64
  transmission: object
  mileage: int64
  fueltype: object
  tax: int64
  mpg: float64
  enginesize: float64
  manufacturer: object
  fail: object

TARGET_COLUMN:
  name: fail