COLUMNS:
  year: int64
  price: int64
  mileage: int64
  tax: int64
  mpg: float64
  enginesize: float64
  model_1series: int64
  model_2series: int64
  model_3series: int64
  model_4series: int64
  model_5series: int64
  model_6series: int64
  model_7series: int64
  model_8series: int64
  model_aclass: int64
  model_a1: int64
  model_a2: int64
  model_a3: int64
  model_a4: int64
  model_a5: int64
  model_a6: int64
  model_a7: int64
  model_a8: int64
  model_accent: int64
  model_adam: int64
  model_agila: int64
  model_amarok: int64
  model_amica: int64
  model_ampera: int64
  model_antara: int64
  model_arteon: int64
  model_astra: int64
  model_auris: int64
  model_avensis: int64
  model_aygo: int64
  model_bclass: int64
  model_b-max: int64
  model_beetle: int64
  model_cclass: int64
  model_c-hr: int64
  model_c-max: int64
  model_cc: int64
  model_clclass: int64
  model_claclass: int64
  model_clcclass: int64
  model_clk: int64
  model_clsclass: int64
  model_caddy: int64
  model_caddylife: int64
  model_caddymaxi: int64
  model_caddymaxilife: int64
  model_california: int64
  model_camry: int64
  model_caravelle: int64
  model_cascada: int64
  model_citigo: int64
  model_combolife: int64
  model_corolla: int64
  model_corsa: int64
  model_crosslandx: int64
  model_ecosport: int64
  model_edge: int64
  model_eos: int64
  model_escort: int64
  model_fabia: int64
  model_fiesta: int64
  model_focus: int64
  model_fox: int64
  model_fusion: int64
  model_gclass: int64
  model_glclass: int64
  model_glaclass: int64
  model_glbclass: int64
  model_glcclass: int64
  model_gleclass: int64
  model_glsclass: int64
  model_gt86: int64
  model_gtc: int64
  model_galaxy: int64
  model_getz: int64
  model_golf: int64
  model_golfsv: int64
  model_grandc-max: int64
  model_grandtourneoconnect: int64
  model_grandlandx: int64
  model_hilux: int64
  model_i10: int64
  model_i20: int64
  model_i30: int64
  model_i40: int64
  model_i800: int64
  model_iq: int64
  model_ix20: int64
  model_ix35: int64
  model_insignia: int64
  model_ioniq: int64
  model_jetta: int64
  model_ka: int64
  model_ka+: int64
  model_kadjar: int64
  model_kamiq: int64
  model_karoq: int64
  model_kodiaq: int64
  model_kona: int64
  model_kuga: int64
  model_landcruiser: int64
  model_mclass: int64
  model_m2: int64
  model_m3: int64
  model_m4: int64
  model_m5: int64
  model_m6: int64
  model_meriva: int64
  model_mokka: int64
  model_mokkax: int64
  model_mondeo: int64
  model_mustang: int64
  model_octavia: int64
  model_proaceverso: int64
  model_passat: int64
  model_polo: int64
  model_prius: int64
  model_puma: int64
  model_q2: int64
  model_q3: int64
  model_q5: int64
  model_q7: int64
  model_q8: int64
  model_rclass: int64
  model_r8: int64
  model_rav4: int64
  model_rs3: int64
  model_rs4: int64
  model_rs5: int64
  model_rs6: int64
  model_rs7: int64
  model_ranger: int64
  model_rapid: int64
  model_roomster: int64
  model_sclass: int64
  model_s-max: int64
  model_s3: int64
  model_s4: int64
  model_s5: int64
  model_s8: int64
  model_slclass: int64
  model_slk: int64
  model_sq5: int64
  model_sq7: int64
  model_santafe: int64
  model_scala: int64
  model_scirocco: int64
  model_sharan: int64
  model_shuttle: int64
  model_streetka: int64
  model_superb: int64
  model_supra: int64
  model_t-cross: int64
  model_t-roc: int64
  model_tt: int64
  model_terracan: int64
  model_tigra: int64
  model_tiguan: int64
  model_tiguanallspace: int64
  model_touareg: int64
  model_touran: int64
  model_tourneoconnect: int64
  model_tourneocustom: int64
  model_transittourneo: int64
  model_tucson: int64
  model_up: int64
  model_urbancruiser: int64
  model_vclass: int64
  model_vectra: int64
  model_veloster: int64
  model_verso: int64
  model_verso-s: int64
  model_viva: int64
  model_vivaro: int64
  model_x-class: int64
  model_x1: int64
  model_x2: int64
  model_x3: int64
  model_x4: int64
  model_x5: int64
  model_x6: int64
  model_x7: int64
  model_yaris: int64
  model_yeti: int64
  model_yetioutdoor: int64
  model_z3: int64
  model_z4: int64
  model_zafira: int64
  model_zafiratourer: int64
  model_i3: int64
  model_i8: int64
  model_180: int64
  model_200: int64
  model_220: int64
  model_230: int64
  transmission_automatic: int64
  transmission_manual: int64
  transmission_other: int64
  transmission_semi-auto: int64
  fueltype_diesel: int64
  fueltype_electric: int64
  fueltype_hybrid: int64
  fueltype_other: int64
  fueltype_petrol: int64
  manufacturer_audi: int64
  manufacturer_bmw: int64
  manufacturer_ford: int64
  manufacturer_hyundi: int64
  manufacturer_merc: int64
  manufacturer_skoda: int64
  manufacturer_toyota: int64
  manufacturer_vauxhall: int64
  manufacturer_volkswagen: int64

TARGET_COLUMN:
  name: fail