COLUMNS:
year: int64
price: int64
mileage: int64
tax: int64
mpg: float64
engineSize: float64
model_ 1 Series: int64
model_ 2 Series: int64
model_ 3 Series: int64
model_ 4 Series: int64
model_ 5 Series: int64
model_ 6 Series: int64
model_ 7 Series: int64
model_ 8 Series: int64
model_ A Class: int64
model_ A1: int64
model_ A2: int64
model_ A3: int64
model_ A4: int64
model_ A5: int64
model_ A6: int64
model_ A7: int64
model_ A8: int64
model_ Accent: int64
model_ Adam: int64
model_ Agila: int64
model_ Amarok: int64
model_ Amica: int64
model_ Ampera: int64
model_ Antara: int64
model_ Arteon: int64
model_ Astra: int64
model_ Auris: int64
model_ Avensis: int64
model_ Aygo: int64
model_ B Class: int64
model_ B-MAX: int64
model_ Beetle: int64
model_ C Class: int64
model_ C-HR: int64
model_ C-MAX: int64
model_ CC: int64
model_ CL Class: int64
model_ CLA Class: int64
model_ CLC Class: int64
model_ CLK: int64
model_ CLS Class: int64
model_ Caddy: int64
model_ Caddy Life: int64
model_ Caddy Maxi: int64
model_ Caddy Maxi Life: int64
model_ California: int64
model_ Camry: int64
model_ Caravelle: int64
model_ Cascada: int64
model_ Citigo: int64
model_ Combo Life: int64
model_ Corolla: int64
model_ Corsa: int64
model_ Crossland X: int64
model_ E Class: int64
model_ EcoSport: int64
model_ Edge: int64
model_ Eos: int64
model_ Escort: int64
model_ Fabia: int64
model_ Fiesta: int64
model_ Focus: int64
model_ Fox: int64
model_ Fusion: int64
model_ G Class: int64
model_ GL Class: int64
model_ GLA Class: int64
model_ GLB Class: int64
model_ GLC Class: int64
model_ GLE Class: int64
model_ GLS Class: int64
model_ GT86: int64
model_ GTC: int64
model_ Galaxy: int64
model_ Getz: int64
model_ Golf: int64
model_ Golf SV: int64
model_ Grand C-MAX: int64
model_ Grand Tourneo Connect: int64
model_ Grandland X: int64
model_ Hilux: int64
model_ I10: int64
model_ I20: int64
model_ I30: int64
model_ I40: int64
model_ I800: int64
model_ IQ: int64
model_ IX20: int64
model_ IX35: int64
model_ Insignia: int64
model_ Ioniq: int64
model_ Jetta: int64
model_ KA: int64
model_ Ka+: int64
model_ Kadjar: int64
model_ Kamiq: int64
model_ Karoq: int64
model_ Kodiaq: int64
model_ Kona: int64
model_ Kuga: int64
model_ Land Cruiser: int64
model_ M Class: int64
model_ M2: int64
model_ M3: int64
model_ M4: int64
model_ M5: int64
model_ M6: int64
model_ Meriva: int64
model_ Mokka: int64
model_ Mokka X: int64
model_ Mondeo: int64
model_ Mustang: int64
model_ Octavia: int64
model_ PROACE VERSO: int64
model_ Passat: int64
model_ Polo: int64
model_ Prius: int64
model_ Puma: int64
model_ Q2: int64
model_ Q3: int64
model_ Q5: int64
model_ Q7: int64
model_ Q8: int64
model_ R Class: int64
model_ R8: int64
model_ RAV4: int64
model_ RS3: int64
model_ RS4: int64
model_ RS5: int64
model_ RS6: int64
model_ RS7: int64
model_ Ranger: int64
model_ Rapid: int64
model_ Roomster: int64
model_ S Class: int64
model_ S-MAX: int64
model_ S3: int64
model_ S4: int64
model_ S5: int64
model_ S8: int64
model_ SL CLASS: int64
model_ SLK: int64
model_ SQ5: int64
model_ SQ7: int64
model_ Santa Fe: int64
model_ Scala: int64
model_ Scirocco: int64
model_ Sharan: int64
model_ Shuttle: int64
model_ Streetka: int64
model_ Superb: int64
model_ Supra: int64
model_ T-Cross: int64
model_ T-Roc: int64
model_ TT: int64
model_ Terracan: int64
model_ Tigra: int64
model_ Tiguan: int64
model_ Tiguan Allspace: int64
model_ Touareg: int64
model_ Touran: int64
model_ Tourneo Connect: int64
model_ Tourneo Custom: int64
model_ Transit Tourneo: int64
model_ Tucson: int64
model_ Up: int64
model_ Urban Cruiser: int64
model_ V Class: int64
model_ Vectra: int64
model_ Veloster: int64
model_ Verso: int64
model_ Verso-S: int64
model_ Viva: int64
model_ Vivaro: int64
model_ X-CLASS: int64
model_ X1: int64
model_ X2: int64
model_ X3: int64
model_ X4: int64
model_ X5: int64
model_ X6: int64
model_ X7: int64
model_ Yaris: int64
model_ Yeti: int64
model_ Yeti Outdoor: int64
model_ Z3: int64
model_ Z4: int64
model_ Zafira: int64
model_ Zafira Tourer: int64
model_ i3: int64
model_ i8: int64
model_180: int64
model_200: int64
model_220: int64
model_230: int64
model_E Class: int64
transmission_Automatic: int64
transmission_Manual: int64
transmission_Other: int64
transmission_Semi-Auto: int64
fuelType_Diesel: int64
fuelType_Electric: int64
fuelType_Hybrid: int64
fuelType_Other: int64
fuelType_Petrol: int64
Manufacturer_Audi: int64
Manufacturer_BMW: int64
Manufacturer_ford: int64
Manufacturer_hyundi: int64
Manufacturer_merc: int64
Manufacturer_skoda: int64
Manufacturer_toyota: int64
Manufacturer_vauxhall: int64
Manufacturer_volkswagen: int64

TARGET_COLUMN: Fail