artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/thekendev/Public_data/raw/main/EDA_cars_data.csv.zip
  Local_data_file: artifacts/data_ingestion/autopredict_cleaned_data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/EDA_cars_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/EDA_cars_data.csv
  transformer_path: artifacts/data_transformation/pipeline.joblib



# model_trainer:
#   root_dir: artifacts/model_trainer
#   train_data_path: artifacts/data_transformation/train.csv
#   test_data_path: artifacts/data_transformation/test.csv
#   model_name: model.joblib
model_trainer:
  root_dir: artifacts/model_trainer
  test_data_path: artifacts/data_transformation/test.csv
  train_data_path: artifacts/data_transformation/train.csv
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json



TARGET_COLUMN:
  name: schema.TARGET_COLUMN